### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8080/api/movies/

###
POST http://localhost:8080/api/movies/
Content-Type: application/json

{
  "title": "Anwar",
  "director": "Amal Neerad"
}

###
POST http://localhost:8080/api/movies/
Content-Type: application/json

{
  "title": "BigB",
  "director": "Amal Neerad"
}