version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: moviereviews
    ports:
      - "5432:5432"
    volumes:
      - moviereviews_data:/var/lib/postgresql/data

volumes:
  moviereviews_data: