spring.application.name=moviereviews
spring.datasource.url=jdbc:postgresql://localhost:5432/moviereviews
spring.datasource.username=admin
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true 

linqapi.token=71703a18-9bed-54f9-97c3-ed85bfa9196c